### ISSUE TITLE
Sound_Issues

### ISSUE THREAD

**Issue by Ulre** [Marsgames/SilverLining#114]
Je n'arrive pas à régler mes problèmes de son, et vous pourrez les régler bien plus vite tout seul que si je vous appelle. J'ai laissé en état ce que j'ai essayé de faire, si il faut que je vire des truc ou quoi vous me dites.

~~Issue 1 : Le son de construction d'obstacle se joue sur le serveur et le client lorsqu'un joueur construit un obstacle --> ObstacleConstructor.cs : 181~~

~~Issue 2 : Le son lorsqu'une unité spawn ne se joue pas sur le client --> SpawnUnits.cs : 128~~

~~Issue 3 : Le son de combat ne se joue pas sur le client --> CombatUnit.cs : 119 - 146 - 162~~

Issue 4 : Le son de capture d'une mine par le client fait une erreur "RPC Function called on client Mine.cs : 113"

**Comment by Ulre** [comment]
Issue 5 : J'ai commenter tout l'appel de l'alerte "BaseInDanger", le son se lance maintenant dès qu'une unité ennemie rentre dans un territoire mais doit juste se lancer lorsqu'elle rentre dans le territoire de la base du joueur. Avec le rework des territoires je ne sais plus comment ça marche

**Comment by Marsgames** [comment]
@Ulre est-ce que l'issue 4 est toujours d'actualité ?
