### ISSUE TITLE
Obstacle_Shortcuts

### ISSUE THREAD

**Issue by PierreMartinent** [Marsgames/SilverLining#121]
L'interface de construction figure les lettres AZERT comme raccourcis plutôt que QSDFG

**Comment by YannigSmagghe** [comment]
LD TEAM

**Comment by Marsgames** [comment]
🕐 Hophophop on fit ça

**Comment by Oriik** [comment]
Aucun LD lit les issues de Git @Marsgames donc t'attends pas à ce qu'ils voient les assignations :sueurr:

**Comment by Marsgames** [comment]
Bah je me dit que s'ils sont assignés et que y'a un commentaire ils doivent recevoir un mail, mais il semblerait que non

**Comment by Marsgames** [comment]
Pour faire des issues y'a du monde mais quand il faut les corriger la y'a plus personne :chance:
