### ISSUE TITLE
Vue tactique

### ISSUE THREAD

**Issue by Marsgames** [Marsgames/SilverLining#133]
En vue tactique on voit les chariot des mines se promener

**Comment by EluardJ** [comment]
En vue tactique, pleins de choses ne fonctionnent pas actuellement : on ne voit pas les icones des unités, on ne voit pas les trails. Par contre on voit bien les icones de points d'intérêts qui changent de couleur.

**Comment by EluardJ** [comment]
On voit aussi les obstacles des murs correctement.
