### ISSUE TITLE
Contextual_UI

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#194]
J'ai aucune idée de comment j'ai déclenché le bug, mais j'ai remarqué qu'à un moment sur le client en build à la place de l'UI contextuelle d'une tour, j'avais les icones des obstacles, et même pas tous du bon camp. J'essayerais de reproduire pour voir d'où ça peut venir. Ca ne faisait rien quand je cliquais sur les icones.
![image](https://user-images.githubusercontent.com/44438289/56581887-42d25c80-65d6-11e9-9e9f-7b6bff1beb3f.png)

**Comment by Oriik** [comment]
Impossible à debug, impossible de savoir comment et pourquoi ça s'est produit. On verra si ça ré arrive
