### ISSUE TITLE
Garrison_selection

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#208]
Quand je sélectionne une mine dans laquelle j'ai des unités en garnison, et qu'ensuite je sélectionne un spawner, l'UI de stock de la garnison est toujours affichée.

**Comment by EluardJ** [comment]
ça fonctionne également en sélection un obstacle constructor

**Comment by vclimpont** [comment]
L'UI d'un obstacle constructor reste affichée si on clique sur un checkpoint / spawnUnit. 
Elle disparaît seulement si on clique sur un autre obstacle constructor
