### ISSUE TITLE
BigGolem_GloryHole

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#226]
Il y a un trou dans le navmesh sur les murs montés (passerelles du coup) uniquement sur les deux murs qui mènent directement au gros golem en mid : 
![image](https://user-images.githubusercontent.com/44438289/56659515-a4a9c980-669d-11e9-94a4-5aa16282ec28.png)

On arrive pas à comprendre pourquoi.. Les autres murs font bien passerelle correctement.

**Comment by Marsgames** [comment]
@EluardJ est-ce que ça empêche les unités de passer ?

**Comment by EluardJ** [comment]
Oui

**Comment by Oriik** [comment]
Taff de LD ça
