### ISSUE TITLE
Obstacle_preview_texture

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#286]
Parfois (pas réussi à déterminer les conditions) la preview du mur a une texture rose manquante au lieu du shader transparent.
Sur le client et le serveur.

**Comment by YannigSmagghe** [comment]
![Capture2](https://user-images.githubusercontent.com/18033828/56890274-4b64e000-6a79-11e9-9720-ac948e6ec09f.JPG)

**Comment by YannigSmagghe** [comment]
![Capture](https://user-images.githubusercontent.com/18033828/56890284-53bd1b00-6a79-11e9-98da-f18cf7ba351e.JPG)
