### ISSUE TITLE
Checkpoint_zone_on_release

### ISSUE THREAD

**Issue by vclimpont** [Marsgames/SilverLining#305]
Des deux côtés (serveur et client), lorsqu'on release les unités d'un checkpoint et qu'il redevient neutre, le checkpoint zone reste quand même affiché. 

https://gyazo.com/ec3176189925949e8256fa424c176749

**Comment by Oriik** [comment]
Alors !
Le code est bien appelé, genre systématiquement ça appelle bien la fonction pour remettre la zone neutre.
D'ailleurs, on voit que le fondu ce fait. Mais il se fait pas jusqu'au bout ?
