### ISSUE TITLE
UI_spawn

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#34]
En build sur le client en fenêtre l'UI de spawn s'est affichée correctement pendant un moment pis après, je sais pas pourquoi =
![image](https://user-images.githubusercontent.com/44438289/55735091-ff49f100-5a20-11e9-9d5e-4d29c1a72caf.png)

**Comment by Marsgames** [comment]
@EluardJ C'est toujours d'actualité ?

**Comment by YannigSmagghe** [comment]
Je ne penses pas
