### ISSUE TITLE
Obstacle_previsualization_the_return

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#354]
Pour le client et le serveur :
-quand un joueur prévisualise un obstacle et qu'un autre construit un autre obstacle sur le même emplacement, tout fonctionne à part que le joueur qui prévisualisait voit toujours le constructor même après la construction de l'obstacle

**Comment by YannigSmagghe** [comment]
Je demande à voir, j'ai fait les test hier et j'ai mis le code en place, si quelqu'un d'autre s'y colle, j'ai mis le deslectpreviewObstacle a la construction de l'obstacle pour tous les joueurs
