### ISSUE TITLE
Cursors_changes_on_client

### ISSUE THREAD

**Issue by EluardJ** [Marsgames/SilverLining#56]
Les curseurs ne changent pas correctement sur les obstacles constructors (les obstacles eux-même c'est ok) sur le client.

**Comment by Marsgames** [comment]
@EluardJ c'est toujours d'actualité ?

**Comment by Marsgames** [comment]
@EluardJ répond

**Comment by Oriik** [comment]
Pas de réponse, bonne réponse.
